version: '3.5'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - frontend
      - backend
    depends_on:
      - database
    environment:
      - "APP_NAME=app"
      - "APP_URL=http://localhost:8080"
      - "DB_DATABASE=homestead"
      - "DB_USERNAME=homestead"
      - "DB_HOST=database"
      - "DB_PASSWORD=secret"
      - "PUBSUB_CONNECTION=kafka"
      - "KAFKA_BROKERS=kafka"

  # NGINX
  web:
    build:
      context: ./
      dockerfile: docker/web/Dockerfile
    working_dir: /var/www
    networks:
      - frontend
    depends_on:
      - app
    volumes:
      - ./public:/var/www/public
    ports:
      - 8082:80

  # The Database
  database:
    build:
      context: ./
      dockerfile: docker/database/Dockerfile
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - backend
    ports:
      - 33063:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=homestead"

  composer:
    image: composer:1.7.2
    command: install --ignore-platform-reqs --no-scripts
    volumes:
      - $PWD:/app

volumes:
  db-volume:

networks:
  frontend:
  backend:
